### ISSUE TITLE
I: Visual Studio 2017 change of compiler tools directory layout

### ISSUE THREAD

**Issue by nea** [kbilsted/NotepadPlusPlusPluginPack.Net#31]
Hey @kbilsted 

I just had to reinstall my machine and with it I updated/installed the newest Visual Studio version 2017. Unfortunately, they made a bigger change in the folder structure. You can read more about it here https://blogs.msdn.microsoft.com/vcblog/2016/10/07/compiler-tools-layout-in-visual-studio-15/

By that, the DllExportTask property 
```
LibToolPath="$(DevEnvDir)\..\..\VC\bin"
```
won't work anymore, as the Dev Environment changed.

I circumvented this for now by importing the current tools version props
```
<Import Condition="Exists('$(DevEnvDir)\..\..\VC\Auxiliary\Build')" Project="$(DevEnvDir)\..\..\VC\Auxiliary\Build\Microsoft.VCToolsVersion.default.props" />  
```
and set the *LibToolPath* to
```
LibToolPath="$(DevEnvDir)\..\..\VC\Tools\MSVC\$(VCToolsVersion)\bin\Host$(Platform)\$(Platform)"
```
You may checkout https://github.com/nea/MarkdownViewerPlusPlus/blob/master/MarkdownViewerPlusPlus/MarkdownViewerPlusPlus.csproj#L280.

I am not 100% convinced by what I did, especially with the host platform... but it works for now ^^' If something like that with 2017 comes up on your end.

Cheers

**Comment by jokedst** [comment]
I had problems compiling too, and I 'm not sure this matters but I don't have C++ installed for my VS2017.
I only had problems with lib.exe, so I set this LibToolPath:
`LibToolPath="$(DevEnvDir)..\..\SDK\ScopeCppSDK\VC\bin"`
and now it works.

**Comment by jokedst** [comment]
Ok, by simply _removing_ the LibBoolPath attribute on the DllExportTask in NppPlugin.DllExport.targets it works for me in both VS2015 and VS2017. :P

**Comment by zizifn** [comment]
Thanks @jokedst @nea And in case someone can't found the path for "[NppPlugin.DllExport.targets](https://github.com/kbilsted/NotepadPlusPlusPluginPack.Net/blob/master/Visual%20Studio%20Project%20Template%20C%23/PluginInfrastructure/DllExport/NppPlugin.DllExport.targets)"

**Comment by moon6969** [comment]
I just wanted to give a little more specific detail for nea's solution above (thanks nea!) since it took a while for me to fully understand exactly what was happening (and my annual rebuild is coming up and I don't want my head to explode again!).

The symptom I experienced was a warning at build time of the unmodified NppManagedPluginDemo:
`NppPlugin.DllExport.targets : warning : Cannot find lib.exe in 'C:\...`

The key change is in file:
`Demo Plugin\NppManagedPluginDemo\PluginInfrastructure\DllExport\NppPlugin.DllExport.targets`
where we want to change the LibToolPath line (since MS has changed the tools folder layout since VS2017).
`LibToolPath="$(DevEnvDir)\..\..\VC\Tools\MSVC\$(VCToolsVersion)\bin\Host$(Platform)\$(Platform)"`

Now $(VCToolsVersion) is not defined in current NppManagedPluginDemo project, so we need to import the props file where it's specified.

The import is done in
`Demo Plugin\NppManagedPluginDemo\NppManagedPluginDemo.VS2015.csproj`
where we can add the below line towards the end under the "Import Project" lines...
`<Import Condition="Exists('$(DevEnvDir)\..\..\VC\Auxiliary\Build')" Project="$(DevEnvDir)\..\..\VC\Auxiliary\Build\Microsoft.VCToolsVersion.default.props" /> `

On a side note I can see in VS2017 Developers command prompt a variable that points to the tools...
`VCToolsInstallDir=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\`

**Comment by kbilsted** [comment]
Many thanks for all the comments. You are right we need support for 2017 soon. I've had a setback with a previous PR that foo'ed things a bit for me. Will revert those changes first and maybe have that as the last visual studio 2015 release. In the mean while, we can start a visual studio 2017 branch if people are really eager

**Comment by kbilsted** [comment]
is the 2017 working for you yet? Just got a new machine, installed the pluginpack and VS2017 and seems to be working here.

**Comment by timop18** [comment]
@noah- it worked for me with pluginpack v0.94 and VS2017 with fresh install

**Comment by noah-** [comment]
> @noah- it worked for me with pluginpack v0.94 and VS2017 with fresh install

Was this with target .net 4.0 or 3.5?

**Comment by timop18** [comment]
The target was .net 4.0

**Comment by noah-** [comment]
Attempted to reinstall vs2017, still no change. Does msbuild standalone need to be installed?

**Comment by timop18** [comment]
Your project is a new pluginpack 0.94 or a migration from an old pluginpack ?

**Comment by noah-** [comment]
I downloaded the 0.94 zip from the releases section and placed it in the template dir. then created new project from the newly added template.

**Comment by timop18** [comment]
OK, so, sorry but I don't see what could be the problem...

**Comment by noah-** [comment]
Figured out the issue, needed to install .net 3.5 (including 2.0) because the NppPlugin.DllExport.MSBuild.dll is referencing msbuild v 2.0.0.0 instead of msbuild v 4.0.0.0

This should be updated.

**Comment by kbilsted** [comment]
@noah-  thanks for reporting. We should test and fix this. Feel free to PR

**Comment by kbilsted** [comment]
@mahee96  vote to close

**Comment by mahee96** [comment]
Closing, since this issue is fixed in the latest master branch.
