### ISSUE TITLE
MyNppplugin2.dll is not compatible With the current verson Of Notepad++

### ISSUE THREAD

**Issue by wuwao1** [kbilsted/NotepadPlusPlusPluginPack.Net#65]
The environment : VS2019 & Notepad++7.9.2 & NppPlugin0.94.00
There seems to be a problem with the environment and template I am using, but there is no way to locate the error.Video below

https://user-images.githubusercontent.com/29857592/104086284-7d3fc980-5291-11eb-921c-3f7a43403170.mp4

**Comment by guidomarcel** [comment]
Hi,
I have exactly the same issue with VS2019. 
[https://community.notepad-plus-plus.org/topic/20562/sqlinform-dll-not-compatible-with-the-current-version-o-n/7]
Maybe NotepadPlusPlusPluginPack.Net  is not ready for VS2019?
Regards
Guido

**Comment by wuwao1** [comment]
Hi Guido
FYI
I tried to compile NPPPlugin0.94.00 using VS2019,VS2017 and VS2015. Only the plugins compiled from VS2015 worked correctly.Thanks.

**Comment by mahee96** [comment]
Are you guys trying to use the zip attached to the releases page ? If so...try to download the sources directly from the main page as zip and use it.

There were lot of changes made to master/main branch but not yet released.

Please let me know if this worked.

**Comment by mahee96** [comment]
@kbilsted can you create a new release out of master/main branch so that people who don't care about the sources can directly download the assets from releases.

Or at least we need to update the README to tell that they need to download straight away from the master branch source since there has been updates after the last release which is 2 years back

**Comment by wuwao1** [comment]
Hi mahee96
FYI
I use VS2019/VS2017/VS2015(both Community versions), and only VS2015 compiles x86 and x64 plugin (the latest source and official release code) properly.Currently I can only use the plugin with VS2015.Thanks.

**Comment by mahee96** [comment]
https://github.com/kbilsted/NotepadPlusPlusPluginPack.Net/archive/master.zip try unzipping this archive and manually copy and replace the files from this into your plugin development folder

**Comment by mahee96** [comment]
@wuwao1 I have created a new pre-release package NppPlugin0.95.00.zip in releases page. It contains the latest fixes after the last release 0.94.00. Try to read the HOW-TO-INSTALL.txt and if it still doesn't work with VS2019 please let me know!

@kbilsted since we were not actively making any progress to this project, I have drafted a new release 0.95.00 and published as a pre-release. If it is not required, please feel free to make changes as you see fit. Thanks.

**Comment by mahee96** [comment]
@guidomarcel please check my last comment and let me know if you still have issues. Thanks!

**Comment by HowkeWayne** [comment]
sorry I have to say the problem remains,
I still can't  Compile the demo successfully.
The environment : VS2019 & Notepad++7.9.5 & v0.95.00 pre-release

**Comment by HowkeWayne** [comment]
![image](https://user-images.githubusercontent.com/18286445/116529465-94252d00-a90f-11eb-82f9-234d8f196234.png)

**Comment by HowkeWayne** [comment]
![image](https://user-images.githubusercontent.com/18286445/116529549-aef7a180-a90f-11eb-8098-508208dc0534.png)

**Comment by kbilsted** [comment]
works on the new 0.95?

**Comment by HowkeWayne** [comment]
> works on the new 0.95?

yes

**Comment by joylin1984** [comment]
0.95  VS2017 npp7.9.5  x64

The same problem occurs

**Comment by mahee96** [comment]
@joylin1984 do you still have the issue? Can you try this if not tried yet?
https://github.com/kbilsted/NotepadPlusPlusPluginPack.Net/releases/download/0.95.00/NppPlugin0.95.00.zip
